baseurl = "https://nextrack.toffee.ro"
languageCode = "ro-RO"
title = "fam. Tofan"

defaultContentLanguage = "ro"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
  
[caches]
  [caches.images]
    dir = ':cacheDir/images'