[ro]
    languageName = "Romană"
    contentDir = "content"
    weight = 1
    [ro.params.head]
        tagline = "Cu toţii avem două vieţi. A doua începe când ne dăm seama că nu avem decât una… "
    [ro.params.social]
        title = "Urmează-mă"
        caption = "Nu contează destinaţia ci călatoria"
    [ro.params.footer]
        # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."

#[en]
#    languageName = "English"
#    contentDir = "content"
#    weight = 2
#    [en.params.head]
#        tagline = "A Hugo Theme"
#    [en.params.social]
#        title = "Follow me"
#        caption = "I work on everything coding and tweet developer memes"
#    [en.params.footer]
#        # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
